{% set name = "nuitka-setuptools2" %}
{% set version = "3.0.0" %}
{% set nuitka_version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/practicalci/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 40c1dd3c8a10ecb25a1a974e8badc495ec6270251ae62c010eef5ab60bc4246d

build:
  noarch: python
  number: 0
  script:
    - pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - nuitka>={{ nuitka_version }}

#test:
#  source_files: 
#    - tests
#  requires:
#    - python
#    - nuitka>={{ nuitka_version }}
#    - cmake
#    - swig
#    - {{ compiler('cxx') }}

about:
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Nuitka setuptools extension.'
  description: |
    Extension to setuptools to run your package through nuitka to produce 
    compiled, faster, obfuscated binary modules.
  doc_url: https://github.com/practicalci/nuitka-setuptools/blob/master/README.rst
  dev_url: https://github.com/practicalci/nuitka-setuptools

extra:
  recipe-maintainers:
    - mjscosta

